Fiorello-PB101/Models/BaseEntity.cs
namespace Fiorello_PB101.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public bool SoftDeleted { get; set; } = false;
        public DateTime CreatedDate { get; set; } = DateTime.Now;
    }
}

Fiorello-PB101/Models/Blog.cs
namespace Fiorello_PB101.Models
{
    public class Blog : BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

Fiorello-PB101/Models/Category.cs
namespace Fiorello_PB101.Models
{
    public class Category : BaseEntity
    {
        public string Name { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

Fiorello-PB101/Models/Expert.cs
using System.ComponentModel.DataAnnotations;

namespace Fiorello_PB101.Models
{
    public class Expert : BaseEntity
    {
        [Required]
        [StringLength(50)]
        public string FullName { get; set; }
        [Required]
        [StringLength(50)]
        public string Position { get; set; }
        public string Image { get; set; }
    }
}

Fiorello-PB101/Models/Product.cs
namespace Fiorello_PB101.Models
{
    public class Product : BaseEntity
    {
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public ICollection<ProductImage> ProductImages { get; set; }
    }
}

Fiorello-PB101/Models/ProductImage.cs
namespace Fiorello_PB101.Models
{
    public class ProductImage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsMain { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

Fiorello-PB101/Models/Slider.cs
namespace Fiorello_PB101.Models
{
    public class Slider : BaseEntity
    {
        public string Image { get; set; }
    }
}

Fiorello-PB101/Models/SliderInfo.cs
using System.ComponentModel.DataAnnotations;

namespace Fiorello_PB101.Models
{
    public class SliderInfo : BaseEntity
    {
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        [Required]
        [StringLength(200)]
        public string Description { get; set; }

        public string Image { get; set; }
    }
}

Fiorello-PB101/ViewModels/Blog/BlogVM.cs
namespace Fiorello_PB101.ViewModels.Blog
{
    public class BlogVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string CreatedDate { get; set; }
    }
}

Fiorello-PB101/ViewModels/Expert/ExpertVM.cs
namespace Fiorello_PB101.ViewModels.Expert
{
    public class ExpertVM
    {
        public string FullName { get; set; }
        public string Position { get; set; }
        public string Image { get; set; }
    }
}

Fiorello-PB101/ViewModels/HomeVM.cs
using Fiorello_PB101.Models;
using Fiorello_PB101.ViewModels.Blog;
using Fiorello_PB101.ViewModels.Expert;

namespace Fiorello_PB101.ViewModels
{
    public class HomeVM
    {
        public IEnumerable<Slider> Sliders { get; set; }
        public SliderInfo SliderInfo { get; set; }
        public IEnumerable<BlogVM> Blogs { get; set; }
        public IEnumerable<ExpertVM> Experts { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<Product> Products { get; set; }
    }
}

Fiorello-PB101/Controllers/BlogController.cs
using Fiorello_PB101.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Fiorello_PB101.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;

        public BlogController(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _blogService.GetAllAsync());
        }
    }
}

Fiorello-PB101/Controllers/BlogDetailController.cs
using Fiorello_PB101.Services.Interfaces;
using Fiorello_PB101.ViewModels.Blog;
using Microsoft.AspNetCore.Mvc;

namespace Fiorello_PB101.Controllers
{
    public class BlogDetailController : Controller
    {
        private readonly IBlogService _blogService;

        public BlogDetailController(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest();
            BlogVM blog = await _blogService.GetByIdAsync((int)id);
            if (blog is null) return NotFound();
            return View(blog);
        }
    }
}

Fiorello-PB101/Controllers/HomeController.cs
using Fiorello_PB101.Services.Interfaces;
using Fiorello_PB101.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Fiorello_PB101.Controllers
{
    public class HomeController : Controller
    {
        private readonly ISliderService _sliderService;
        private readonly IBlogService _blogService;
        private readonly IExpertService _expertService;
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;

        public HomeController(
            ISliderService sliderService,
            IBlogService blogService,
            IExpertService expertService,
            ICategoryService categoryService,
            IProductService productService
            )
        {
            _sliderService = sliderService;
            _blogService = blogService;
            _expertService = expertService;
            _categoryService = categoryService;
            _productService = productService;
        }
        public async Task<IActionResult> Index()
        {
            HomeVM model = new()
            {
                Sliders = await _sliderService.GetAllAsync(),
                SliderInfo = await _sliderService.GetSliderInfoAsync(),
                Blogs = await _blogService.GetAllAsync(3),
                Experts = await _expertService.GetAllAsync(),
                Categories = await _categoryService.GetAllAsync(),
                Products = await _productService.GetAllAsync()
            };

            return View(model);
        }

    }
}

Fiorello-PB101/Controllers/ProductController.cs
using Fiorello_PB101.Models;
using Fiorello_PB101.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Fiorello_PB101.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index(int? id)
        {
            if (id is null) return BadRequest(); 

            Product product = await _productService.GetByIdAsync((int)id);

            if (product is null) return NotFound();

            return View(product);
        }
    }
}

Fiorello-PB101/Views/Blog/Index.cshtml
@model IEnumerable<BlogVM>
@{
    ViewData["Title"] = "Blog";
}

<section id="blog">
    <div class="container">
        <div class="row py-5">
            <div class="offset-lg-3 col-lg-6">
                <div class="section-title">
                    <h1>From our Blog</h1>
                    <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                        love. Let us arrange
                        a smile for you.</p>
                </div>
            </div>
        </div>
        <partial name="_BlogPartial"/>
    </div>
</section>

Fiorello-PB101/Views/BlogDetail/Index.cshtml
@model BlogVM
@{
    ViewData["Title"] = "Index";
}

@section css{
    <link rel="stylesheet" href="~/css/blogdetail.css">
}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container pb50">
    <div class="row">
        <div class="col-md-9 mb40">
            <article>
                <img src="~/img/@Model.Image" alt="" class="img-fluid mb30">
                <div class="post-content">
                    <h3>@Model.Title</h3>
                    <ul class="post-meta list-inline">
                        <li class="list-inline-item">
                            <i class="fa fa-user-circle-o"></i> <a href="#">John Doe</a>
                        </li>
                        <li class="list-inline-item">
                            <i class="fa fa-calendar-o"></i> <a href="#">@Model.CreatedDate</a>
                        </li>
                        <li class="list-inline-item">
                            <i class="fa fa-tags"></i> <a href="#">Bootstrap4</a>
                        </li>
                    </ul>
                    <p>@Model.Description </p>
                    <ul class="list-inline share-buttons">
                        <li class="list-inline-item">Share Post:</li>
                        <li class="list-inline-item">
                            <a href="#" class="social-icon-sm si-dark si-colored-facebook si-gray-round">
                                <i class="fa fa-facebook"></i>
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="social-icon-sm si-dark si-colored-twitter si-gray-round">
                                <i class="fa fa-twitter"></i>
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#" class="social-icon-sm si-dark si-colored-linkedin si-gray-round">
                                <i class="fa fa-linkedin"></i>
                                <i class="fa fa-linkedin"></i>
                            </a>
                        </li>
                    </ul>
                    <hr class="mb40">
                    <h4 class="mb40 text-uppercase font500">About Author</h4>
                    <div class="media mb40">
                        <i class="d-flex mr-3 fa fa-user-circle fa-5x text-primary"></i>
                        <div class="media-body">
                            <h5 class="mt-0 font700">Jane Doe</h5> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        </div>
                    </div>
                    <hr class="mb40">
                    <h4 class="mb40 text-uppercase font500">Comments</h4>
                    <div class="media mb40">
                        <i class="d-flex mr-3 fa fa-user-circle-o fa-3x"></i>
                        <div class="media-body">
                            <h5 class="mt-0 font400 clearfix">
                                <a href="#" class="float-right">Reply</a>
                                Jane Doe
                            </h5> Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        </div>
                    </div>
                    <div class="media mb40">
                        <i class="d-flex mr-3 fa fa-user-circle-o fa-3x"></i>
                        <div class="media-body">
                            <h5 class="mt-0 font400 clearfix">
                                <a href="#" class="float-right">Reply</a>
                                Jane Doe
                            </h5> Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        </div>
                    </div>
                    <div class="media mb40">
                        <i class="d-flex mr-3 fa fa-user-circle-o fa-3x"></i>
                        <div class="media-body">
                            <h5 class="mt-0 font400 clearfix">
                                <a href="#" class="float-right">Reply</a>
                                Jane Doe
                            </h5> Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        </div>
                    </div>
                    <hr class="mb40">
                    <h4 class="mb40 text-uppercase font500">Post a comment</h4>
                    <form role="form">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="John Doe">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" class="form-control" placeholder="john@doe.com">
                        </div>
                        <div class="form-group">
                            <label>Comment</label>
                            <textarea class="form-control" rows="5" placeholder="Comment"></textarea>
                        </div>
                        <div class="clearfix float-right">
                            <button type="button" class="btn btn-primary btn-lg">Submit</button>
                        </div>
                    </form>
                </div>
            </article>
            <!-- post article-->

        </div>
        <div class="col-md-3 mb40">
            <div class="mb40">
                <form>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search..." aria-describedby="basic-addon2">
                        <button class="input-group-addon" id="basic-addon2"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
            <!--/col-->
            <div class="mb40">
                <h4 class="sidebar-title">Categories</h4>
                <ul class="list-unstyled categories">
                    <li><a href="#">Rent</a></li>
                    <li><a href="#">Sale</a></li>
                    <li class="active">
                        <a href="#">Apartment</a>
                        <ul class="list-unstyled">
                            <li><a href="#">Office</a></li>
                            <li><a href="#">Godown</a></li>
                            <li><a href="#">Gerage</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Top Rating</a></li>
                    <li><a href="#">Trending</a></li>
                    <li><a href="#">Newest Properties</a></li>
                </ul>
            </div>
            <!--/col-->
            <div>
                <h4 class="sidebar-title">Latest News</h4>
                <ul class="list-unstyled">
                    <li class="media">
                        <img class="d-flex mr-3 img-fluid" width="64" src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Generic placeholder image">
                        <div class="media-body">
                            <h5 class="mt-0 mb-1"><a href="#">Lorem ipsum dolor sit amet</a></h5> April 05, 2017
                        </div>
                    </li>
                    <li class="media my-4">
                        <img class="d-flex mr-3 img-fluid" width="64" src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="Generic placeholder image">
                        <div class="media-body">
                            <h5 class="mt-0 mb-1"><a href="#">Lorem ipsum dolor sit amet</a></h5> Jan 05, 2017
                        </div>
                    </li>
                    <li class="media">
                        <img class="d-flex mr-3 img-fluid" width="64" src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="Generic placeholder image">
                        <div class="media-body">
                            <h5 class="mt-0 mb-1"><a href="#">Lorem ipsum dolor sit amet</a></h5> March 15, 2017
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

Fiorello-PB101/Views/Home/Index.cshtml
@model HomeVM
@{
    ViewData["Title"] = "Home";
}

  <!-- MAIN START -->

    <main>

        <!-- SLIDER START -->

        <section id="slider">
            <div class="owl-carousel slider">
                @foreach (var item in Model.Sliders)
                {
                    <div> <img src="~/img/@item.Image" alt=""> </div>
                }
               
            </div>
            <div class="container context pl-lg-5 ml-lg-3">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="text">
                          @Html.Raw(Model.SliderInfo.Title)
                            <p class="text-black-50 d-none d-sm-block">@Model.SliderInfo.Description </p>
                        </div>
                        <div class="img">
                            <img src="~/img/@Model.SliderInfo.Image" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SLIDER END -->

        <!-- PRODUCTS START -->

        <section id="products">
            <div class="container">
                <div class="row pt-5">
                    <div class="col-12 d-flex justify-content-between">
                        <ul class="category-mobile d-md-none list-unstyled">
                            <li>
                                <a href="" class="categories mr-2">Categories</a>
                                <i class="fas fa-caret-down"></i>
                                <ul class="category list-unstyled" style="display: none;">
                                    <li><a href="" data-id="all">All</a></li>
                                    <li><a href="" data-id="popular">Popular</a></li>
                                    <li><a href="" data-id="winter">Winter</a></li>
                                    <li><a href="" data-id="various">Various</a></li>
                                    <li><a href="" data-id="exotic">Exotic</a></li>
                                    <li><a href="" data-id="green">Greens</a></li>
                                    <li><a href="" data-id="cactuse">Cactuses</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="category d-none d-md-flex list-unstyled">
                            <li><a href="" data-id="all">All</a></li>
                           @foreach (var item in Model.Categories)
                            {
                                <li><a href="" data-id="@item.Id">@item.Name</a></li>
                            }
                           
                        </ul>
                        <ul class="list-unstyled">
                            <li>
                                <a href="" class="mr-2">Filter</a>
                                <i class="fas fa-caret-down"></i>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                   @foreach (var item in Model.Products)
                   {
                    <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
                        <div class="product-item text-center" data-id="@item.CategoryId">
                            <div class="img">
                                <a asp-controller="Product" asp-action="Index" asp-route-id="@item.Id">
                                    <img src="~/img/@item.ProductImages.FirstOrDefault(m=> m.IsMain)?.Name" class="img-fluid" alt="">
                                </a>
                            </div>
                            <div class="title mt-3">
                                <h6>@item.Name</h6>
                            </div>
                            <div class="price">
                                <span class="text-black-50">Add to cart</span>
                                <span class="text-black-50">$@item.Price.ToString(@item.Price % 1 == 0 ? "0" : "0.00")</span>
                            </div>
                        </div>
                    </div>

                   }
                </div>
            </div>
        </section>

        <!-- PRODUCTS END -->

        <!-- ABOUT START -->

        <section id="about">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-lg-6">
                        <div class="img">
                            <img src="~/img/h3-video-img.jpg" class="img-fluid" alt="">
                            <div
                                class="player position-absolute rounded-circle d-flex align-items-center justify-content-center">
                                <i class="fas fa-play fa-lg"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-text mt-5 mt-lg-0 px-lg-5">
                            <h1>Suprise Your <span>Valentine!</span> Let us arrange a smile.</h1>
                            <p class="py-3">Where flowers are our inspiration to create lasting memories. Whatever the
                                occasion...</p>
                            <ul class="list-unstyled">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Hand picked just
                                    for you.</li class="mt-3">
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Unique flower
                                    arrangements</li>
                                <li class="mt-3"><img src="~/img/h1-custom-icon.png" class="mr-2" alt=""> Best way to say
                                    you care.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ABOUT END -->

        <!-- EXPERTS START -->

        <section id="experts">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>Flower Experts</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">
                    @foreach (var item in Model.Experts)
                    {
                        <div class="col-md-6 col-lg-3">
                            <div class="item text-center">
                                <div class="img">
                                    <img src="~/img/@item.Image" class="img-fluid rounded-circle" alt="">
                                </div>
                                <div class="text mt-3">
                                    <h6>@item.FullName.ToUpper()</h6>
                                    <p class="text-black-50">@item.Position</p>
                                </div>
                            </div>
                        </div>
                    }
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3"></div>
                </div>
            </div>
        </section>

        <!-- EXPERTS END -->

        <!-- SUBSCRIBE START -->

        <section id="subscribe">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-12">
                        <div class="content text-center py-5">
                            <h3>Join The Colorful Bunch!</h3>
                            <div class="form-group d-flex justify-content-center flex-wrap mt-5">
                                <input type="email" placeholder="Email Address" class="form-control-lg rounded-0">
                                <button class="btn btn-danger btn-lg rounded-0 px-5 mt-3 mt-sm-0">Subscribe</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SUBSCRIBE END -->

        <!-- BLOG START -->

        <section id="blog">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>From our Blog</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
              <partial name="_BlogPartial" model="@Model.Blogs"/>
            </div>
        </section>

        <!-- BLOG END -->

        <!-- SAY START -->

        <section id="say">
            <div class="container">
                <div class="row py-5 justify-content-center">
                    <div class="col-md-8 col-xl-6">
                        <div class="owl-carousel say">
                            <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/testimonial-img-1.png" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus
                                            lingua. </i>
                                    </div>
                                    <div class="author">
                                        <h6>Anna Barnes</h6>
                                        <p class="text-black-50">Florist</p>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/testimonial-img-2.png" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
                                            ligula eget. </i>
                                    </div>
                                    <div class="author">
                                        <h6>Jasmine White</h6>
                                        <p class="text-black-50">Florist</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SAY END -->

        <!-- INSTAGRAM START -->

        <section id="instagram">
            <div class="owl-carousel instagram">
                <div><img src="~/img/instagram1.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram2.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram3.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram4.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram5.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram6.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram7.jpg" class="img-fluid" alt=""></div>
                <div><img src="~/img/instagram8.jpg" class="img-fluid" alt=""></div>
            </div>
            <div class="hastag bg-light text-muted py-2 px-3">
                #FIORELLO
            </div>
        </section>

        <!-- INSTAGRAM END -->

    </main>

    <!-- MAIN END -->

Fiorello-PB101/Views/Shared/_BlogPartial.cshtml
@model IEnumerable<BlogVM>

<div class="row pb-5">
    @foreach (var item in Model)
    {
        <div class="col-md-6 col-lg-4">
                <div class="item">
                    <div class="img position-relative">
                        <a asp-controller="BlogDetail" asp-action="Index" asp-route-id="@item.Id">
                        <img src="~/img/@item.Image" class="img-fluid" alt="">
                        </a>
                        <div class="date rounded bg-light position-absolute py-1 px-2">
                            <span>@item.CreatedDate</span>
                        </div>
                    </div>
                    <div class="text mt-3 text-center px-5">
                        <h5>@item.Title</h5>
                        <p class="text-black-50">@item.Description</p>
                    </div>
                </div>
        </div>
    }
                   
</div>